[features]
seeds = false
skip-lint = false
[programs.localnet]
otc_contract = "4n7HpbdQgJC2Gc8k1Tz7fi8oV7ARFEMThL7nAa3s418z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/atahanyild/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
